# Welcome to Jekyll!


# In addition to these settings, there is a file _data/tokens-template.yml
# that you'll want to customize for your site. It's named 'tokens' because
# that was it's original purpose, but because tokens.yml is .gitexcluded, it's
# a good place to store your site-specific data that you'd rather not have
# forked or cloned. Of course, that means you'd want to back it up elsewhere.

# Also, for your post bylines, add author info for yourself in `_data/authors.yml`.
# (Using that method instead of site.owner, in case your posts get cloned with your repo.)

# Site settings
title: Aprende a Generar Dinero Usando Internet
description: Si tienes dinero y no tienes ideas el dinero se va, pero si no tienes dinero y tienes ideas el dinero llega
owner:
  name: Arcom Internacional # or company name
  url: "http://arcom.com" # your URL
first_published: 2010 # if migrating another site, the year of your first publish
                      # Must be a 4-digit integer year (math is used on it)
url: "https://aprendegenerardinero.github.io" # the base hostname & protocol for this site
baseurl: "" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.
lang: en-us # used in HTML lang attributes

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: ¡HOLA TERRANO! – ¡qué tal? –  
  text: GANAR DINERO EN INTERNET – ¿ES CIERTO? ¿ES FALSO? ¿ES MODA?
        ¡DÉJAME DECIRTE QUE ES TOTALMENTE CIERTO!
        ¡Y DÉJAME DECIRTE QUE TIENE TIEMPO YA OCURRIENDO!
  content: Quiero invitarte a un proyecto de ganancia de dinero por internet. Algunos de mis amigos y conocidos saben que desde el 1º de junio decidí investigar cómo hacer dinero a través de internet y que hice tan bien mi tarea, que desde el 1º de octubre 2019 ya no trabajo como técnico en computación, que estoy dedicado ya 100% a generar dinero a través de internet. Presta mucha atención a ésta invitación porque te aseguro que es una oportunidad para ti de hacer dinero. Lo que no entiendas, lo buscas por Google o me lo preguntas directamente a mí que con gusto te aclaré todas tus dudas.


# - displayed at the bottom
closing-head: Un abrazo y a invertir que no nos cuesta nada.
closing-para: Argento Armiloj
              CEO de Arcom Internacional
              Productora de Contenidos y Negocios por Internet
              +584142908484
              aprendegenerardinero@gmail.com


# on all pages (and the first three you list display with greeting, if included)
social:
  twitter: https://twitter.com/arcom
  facebook-official: https://facebook.com/arcom
  google-plus-square: https://plus.google.com/u/0/+_username_
  email: /contact/ 
  youtube-square: https://youtube.com/arcom

# - title for your blog's featured posts
features-title: Informacion destacada

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here. (I didn't spend time dealing with spaces
# and full paths of the various OSes in compose.rb. For my Windows
# environment, I just put a subl.cmd file in my PATH that points to the full
# path to Sublime's subl.exe.) Also, put your most common post extension.
compose:
  editor: subl
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# Github pages posts future posts by default.
# You'll want to move the user guide posts to _drafts if you set this to true.
future: false

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
markdown: kramdown
#sass:
#  style: compressed
exclude: ['site.bat','compose.rb','README.md']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
      #permalink: /:slug/ # dunna work. See github.com/jekyll/jekyll/issues/2280
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
